<?php
/**
* Author:
* Michael Kefeder
*/

$labels = array();
$labels['label'] = 'Étiquette';

$labels['tb_label_options'] = 'Étiquettes';
$labels['tb_label_enable_option'] = 'Activer l\'extension';
$labels['tb_label_button_label'] = 'Étiquettes';
$labels['tb_label_button_title'] = 'Affecter des étiquettes aux messages';
$labels['tb_label_contextmenu_title'] = 'Étiquettes';
$labels['tb_label_style_option'] = 'Style graphique';
$labels['tb_label_label'] = "Étiquette";